site_name: pycomole
repo_url: https://github.com/ziyunli/pycomole
watch:
  - src

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Introduction: 'index.md'
  - Notes:
    - "notes/strings.md"
  - Solutions:
    - "solutions/cs9.md"
  - changelog.md


markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_signature_annotations: true
            show_source: true
